### ISSUE TITLE
More flexible multi-line input in ExampleInput

### ISSUE THREAD

**Issue by GalAster** [MMA-ForScience/ForScience#6]
The current multi-line input is like this: 
```Mathematica
Examples[test, "Basic examples"] = {
   {
    "Multple input lines:",
    ExampleInput[
     "Plot[
     x^2,
     {x,0,1}
     ]"
     ]
    }
   };
DocumentationBuilder[test]
```

But when I use metaprogramming, it is inconvenient to manipulate strings.
 I hope to support such a grammar: 

```Mathematica
ExampleInput[
  MultLine@expression1,
  Expression2
  ]
```

MultLine can format an expression, probably can be defined as

```Mathematica
MultLine[expr_, separator_ : N] := Block[
	{box, token},
	token = If[StringQ@separator , "\"" ~~ separator ~~ "\"", ToString@separator];
	box = ToBoxes[expr] //. {{a___, token, ",", b___} :> {a, "\[IndentingNewLine]", b}};
	box = box //. {{a___, ",", token} :> {a, "\[IndentingNewLine]"}};
	CellPrint@Cell[BoxData@box, "Output"];
];
```

![tim 20181122132820](https://user-images.githubusercontent.com/17541209/48883372-8293ed00-ee5a-11e8-90a1-4efddfb2485e.png)

**Comment by lukas-lang** [comment]
Thank you for your suggestion, entering complex inputs as string is indeed not ideal...
In latest version of the paclet (0.75.2) I have added support for automatic line wrapping using the `"Multiline"` option of `ExampleInput`:

![image](https://user-images.githubusercontent.com/33105866/49141802-bad27a00-f2f7-11e8-8aad-71500c5cc19c.png)

You can also specify a bigger line width limit:
![image](https://user-images.githubusercontent.com/33105866/49141841-d6d61b80-f2f7-11e8-8366-337bf984eddd.png)

(You can specify patterns on which to break, see the documentation for more examples)

As you can see, `ExampleInput` expressions now also typeset nicely, so you can directly see how something will look in the final documentation notebook.

The current implementation of the line breaking is of course not as flexible as what you proposed, but it should be a bit easier to use. Let me know if you have a use-case that requires more flexibility. Also, there might still be some issues with the automatic width estimation, please let me know if you encounter any problems.

**Comment by GalAster** [comment]
Perfect, enough for me!
