### ISSUE TITLE
Can I control the opening or closing of a cell?

### ISSUE THREAD

**Issue by GalAster** [MMA-ForScience/ForScience#7]
Sometimes if some of the instructions are short, I would like the `DetailsCell` or `ExamplesCell` to be in an opening state. 
Is this option achievable?

---

And here's something interesting, maybe helpful to your `CompatibilityChecker`:

https://resources.wolframcloud.com/FunctionRepository/resources/SymbolDependencies

**Comment by lukas-lang** [comment]
Thanks for the suggestion and sorry for the delay in answering. I thought I could quickly implement this, but I ran into a few design decisions and nasty bugs…

Anyway, the latest version of the paclet has options to control the state of the Details/Examples sections.

You can set the defaults with
```Mathematica
SetDocumentationOptions[Details,Open->...]
SetDocumentationOptions[Examples,Open->...]
```
You can also change the settings for individual symbols using
```Mathematica
SetDocumentationOptions[Details[sym],Open->...]
SetDocumentationOptions[Examples[sym],Open->...]
```
See the documentation of `Details`/`Examples` for more information on the supported settings.
